### ISSUE TITLE
Poisson - add comparison of two distributions

### ISSUE THREAD

**Issue by vsoch** [tabakg/fun_tutorials#1]
For [Poisson](https://github.com/tabakg/fun_tutorials/blob/master/Poisson%20Distribution%20--%20an%20intuitive%20intro.ipynb) it would be good to compare the experiment generated and "actual" distribution by way of some statistical test to supplement the visual comparison.

**Comment by tabakg** [comment]
I added a statistical test using the Kolmogorov-Smirnov test.
